# ─────────────────────────────────────────────
# application.properties
#
# Configuración principal de Spring Boot.
# Para desarrollo local usa: application-local.properties
# Para producción usa:       application-prod.properties
#
# Propiedades comunes a todos los perfiles:
#   spring.application.name   → nombre de la app
#   server.port               → puerto del servidor (default 8080)
#   spring.datasource.*       → conexión a BD
#   spring.jpa.*              → configuración de Hibernate/JPA
#   spring.security.*         → configuración de seguridad
# ─────────────────────────────────────────────
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
logging.level.org.springframework.boot.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG


spring.application.name=proyecto-fullstack
app.version=1.0.1:2026.10.09: log4j, databaseFixes
server.port=8080

#DB
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=cybgor
spring.datasource.password=pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.log.path=/var/log/demo/backendControlVotaciones.log
logging.file.name=${app.log.path}

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS,America/Mexico_City} %-5level [%thread] %logger{36} - %msg%n
logging.level.root=INFO
logging.level.com.empresa.app=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG


